### ISSUE TITLE
中文乱码问题好像配置不了字体

### ISSUE THREAD

**Issue by fucktx** [Mindinventory/Golang-HTML-TO-PDF-Converter#1]
你好，我测试了下导出中文全是乱码，英文正常，源代码中好像不支持自定义中文字体路径？

**Comment by malvikiran** [comment]
@xhochipe 好，让我检查一下。 如果它不支持中文字体，那么我将发布更新版本。

**Comment by malvikiran** [comment]
是的，它支持中文。 我来附上截图。https://ibb.co/Np64B3P

**Comment by fucktx** [comment]
@malvikiran 是支持中文，您有微信嘛，我发您一份我这边的html给您

**Comment by malvikiran** [comment]
@xhochipe 您可以使用网站（https://ibb.co）向我发送您的屏幕截图。

**Comment by fucktx** [comment]
@malvikiran  抱歉，国内打不开您发的那个网站  1.html
[TestGeneratePdfFromStdinSimple.pdf](https://github.com/Mindinventory/Golang-HTML-TO-PDF-Converter/files/3280270/TestGeneratePdfFromStdinSimple.pdf)

[1.txt](https://github.com/Mindinventory/Golang-HTML-TO-PDF-Converter/files/3280271/1.txt)


TestGeneratePdfFromStdinSimple.pdf
您好，这是我的html，github不让上传.html文件，我只好把.html改成.txt

**Comment by malvikiran** [comment]
@xhochipe 你能发送你的HTML代码格式吗？ 目前我无法在你的txt文件中看到任何html标签。

**Comment by fucktx** [comment]
@malvikiran 里面是p标签和其他一些div等标签

**Comment by maxyzli** [comment]
@malvikiran 

這是 HTML 的代碼： https://www.dropbox.com/s/5pmfeupfusz8nqn/1.html?dl=0

And the generated pdf will look like this.

![Screen Shot 2019-06-12 at 16 16 56](https://user-images.githubusercontent.com/11765228/59334636-840d0000-8d2d-11e9-8079-ee69172645b8.png)

**Comment by fucktx** [comment]
@malvikiran 您好，我知道怎么解决了，我直接把html头编码设置了就正常，非常感谢您

**Comment by malvikiran** [comment]
@xhochipe 究竟。 很好
