### ISSUE TITLE
there is no way to pass wkhtmltopdf args

### ISSUE THREAD

**Issue by jesson1** [Mindinventory/Golang-HTML-TO-PDF-Converter#6]

**Comment by adityasinh-mi** [comment]
Hello @jesson1,

I'm happy to inform you that the issue regarding passing wkhtmltopdf args has been solved. The latest update includes a new feature that allows users to pass arguments to wkhtmltopdf. Please update to the latest version and try passing the arguments again. If you still encounter any issues, please feel free to reopen the issue, and we will be happy to assist you further.

Thank you for bringing this to our attention, and we appreciate your patience while we resolved this matter.
